# This is a basic workflow to help you get started with Actions

name: windows

# Controls when the action will run. Triggers the workflow
# on push or pull request events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made of jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks executed as part of the job
    steps:
      # Checks-out your repo under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Visual Studio shell (path to lib.exe)
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Setup prerequisites (windows)
        run: |
          echo 'C:\msys64\usr\bin' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          C:\msys64\usr\bin\pacman -S --noconfirm zip unzip

      - name: Compile blink1-tool
        shell: bash
        run: make

      - name: Package blink1-tool
        shell: bash
        run: make package

      - name: Upload blink1-tool artifact
        uses: actions/upload-artifact@v3
        with:
          name: blink1-tool-artifacts
          path: blink1*.zip
          # retention-days: 5

      - name: Compile blink1-tiny-server
        shell: bash
        run: make blink1-tiny-server

      - name: Package blink1-tiny-server
        shell: bash
        run: make package-tiny-server

      - name: 'Upload blink1-tiny-server artifact'
        uses: actions/upload-artifact@v3
        with:
          name: blink1-tiny-server-artifacts
          path: blink1*.zip
          # retention-days: 5

      - name: Compile blink1control-tool
        shell: bash
        run: make blink1control-tool

      - name: Package blink1control-tool
        shell: bash
        run: make package-blink1control-tool

      - name: 'Upload blink1control-tool artifact'
        uses: actions/upload-artifact@v3
        with:
          name: blink1-tool-windows-all-artifacts
          path: blink1*.zip
          # retention-days: 5
